name: ARMv7 build

on:
  push:
    branches: [master]

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: armv7-unknown-linux-gnueabihf
      - name: Install libclang
        run: sudo apt-get install libclang-dev
      - name: Find libclang.so
        run: find $GITHUB_WORKSPACE -iname "libclang.so" -print
#       - name: Build
#         run: cargo build --release --target armv7-unknown-linux-gnueabihf
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           files: |
#             target/armv7-unknown-linux-gnueabihf/release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
